/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CblkRdr */

#ifndef _Included_CblkRdr
#define _Included_CblkRdr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CblkRdr
 * Method:    blkrdr
 * Signature: (IIILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CblkRdr_blkrdr
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     CblkRdr
 * Method:    totallines
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_CblkRdr_totallines
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
